### ISSUE TITLE
"Bloomberg Style" seems to be broken on demo page

### ISSUE THREAD

**Issue by Qix-** [asvd/viewport#2]
The demo page, at least on Chrome, seems to have a broken Bloomberg style (it never switches away from Astronomy).

**Comment by asvd** [comment]
Can't reproduce (Chrome 48). Which Chrome version do you have? Is there any messages on console?

**Comment by Qix-** [comment]
50.0.2661.102 (64-bit) on OS X. No errors in the console.

![Demo](http://g.recordit.co/SSh6sa3N9k.gif)

**Comment by asvd** [comment]
ok, reproduced

**Comment by asvd** [comment]
fixed in v0.0.5
